version: 2

defaults: &defaults
  docker:
    - image: hchauvin/multi-language-lib-build-env

third_party: &third_party
  name: Third Party
  command: |
    mkdir -p third_party
    cd third_party
    rm -rf conan-vscodepropertiesgen
    git clone https://github.com/mkovalchik/conan-vscodepropertiesgen.git
    cd conan-vscodepropertiesgen
    conan export . vscodepropertiesgen/0.1@mkovalchik/stable

jobs:
  cpp:
    <<: *defaults
    steps:
      - checkout
      - run: *third_party
      - run:
          name: build_and_test
          command: |
            cd cpp
            mkdir -p build
            cd build

            conan install .. --build=outdated
            conan build ..
            make test
            bin/test
      - run:
          name: test_package
          command: |
            cd cpp
            conan test_package example/0.1.0@hchauvin/test
  R:
    <<: *defaults
    steps:
      - checkout
      - run: *third_party
      - run:
          name: build_and_test
          command: |
            cd ./R
            R CMD INSTALL .
            Rscript -e "example::str_split('hello world')"
            Rscript -e "devtools::test()"
  python:
    <<: *defaults
    steps:
      - checkout
      - run: *third_party
      - run:
          name: build_and_test
          command: |
            cd python
            ./setup.py develop
            ./setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - cpp
      - R
      - python
