version: 2
gcc-6:
  docker:
    - image: conanio/gcc6
  steps:
    - checkout
    - run:
        name: Build Conan package
        command: |
          sudo pip install --upgrade conan
    - run:
        name: C++
        command: |
          cd cpp
          mkdir -p build
          cd build

          conan install .. --build=outdated
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
          cmake --build .. --target test
          bin/test
    - run:
        name: R
        command: |
          cd R
          R -e "devtools::load_all(); example::str_split('hello world')"
          R -e "devtools::test()"
    - run:
        name: Python
        command: |
          cd python
          ./setup.py develop
          ./setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-6
