version: 2
jobs:
  gcc-6:
    docker:
      - image: conanio/clang8-x86
    # TODO: Add cache
    steps:
      - checkout
      - run:
          name: Build Conan package
          command: |
            sudo pip install --upgrade conan
      - run:
          name: Third Party
          command: |
            mkdir -p third_party
            cd third_party
            rm -rf conan-vscodepropertiesgen
            git clone https://github.com/mkovalchik/conan-vscodepropertiesgen.git
            cd conan-vscodepropertiesgen
            conan export . vscodepropertiesgen/0.1@mkovalchik/stable
      # - run:
      #     name: C++
      #     command: |
      #       cd cpp
      #       mkdir -p build
      #       cd build

      #       conan install .. --build=outdated
      #       cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
      #       cmake --build .. --target test
      #       bin/test
      - run:
          name: R
          command: |
            echo "conannn $(dirname $(which conan))"
            sudo apt-get update # ttt
            sudo bash -c "DEBIAN_FRONTEND=noninteractive apt-get install -y r-base libxml2-dev libcurl4-openssl-dev"
            cd R
            # TODO: No sudo (https://stackoverflow.com/questions/32540919/library-is-not-writable)
            sudo R -e "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
            export PATH=$(dirname $(which conan)):$PATH
            sudo R -e "devtools::load_all(); example::str_split('hello world')"
            R -e "devtools::test()"
      - run:
          name: Python
          command: |
            cd python
            ./setup.py develop
            ./setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-6
